version: '3.8'

services:
  nginx:
    image: nginx:1.21
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8080:8080"
