version: '3.8'

services:
  nginx:
    image: nginx:1.21
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  datadog:
    build: ./datadog
    container_name: datadog_agent
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.eu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./datadog/conf.d/nginx.d:/etc/datadog-agent/conf.d/nginx.d
    depends_on:
      - nginx
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
