---
- name: Provision and configure AWS EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: your_key_name
        instance_type: t2.micro
        image_id: ami-0c55b159cbfafe1f0
        wait: yes
        region: us-east-1
        count: 1
        instance_tags:
          Name: nginx_server
      register: ec2

    - name: Add new instance to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"
      delegate_to: localhost

- name: Configure Nginx on EC2 instance
  hosts: launched
  roles:
    - nginx
